<?php 
/* 
Template Name: FurnitureTemplate 
*/ 
?>


<?php get_header() ?>

	<div id="container">
	<div id="leftbar">
	<img src="<?php bloginfo('stylesheet_directory'); ?>/images/SandraJaneLogo.gif">
	<?php wp_nav_menu( array( 'theme_location' => 'left-menu' ) ); ?>
	<img src="<?php bloginfo('stylesheet_directory'); ?>/images/SandraJaneShop.gif">
	<div class="address">46-48 King Street<br />Cambridge</div>
	</div><!-- #leftbar -->
		<div id="content">
		<?php the_post() ?>
			
			<h1 class="furnitureh1"><?php /* Title generated by Wordpress */ the_title() ?></h1>
			<div id="post">
			<?php /* Content generated by Wordpress */ the_content() ?>
			</div>
			<h1 class="furnitureh1">01223 323211 | <a href="mailto:contact@sandrajane.co.uk">contact@sandrajane.co.uk</a></h1>
			<div id="decoration">
				<img src="<?php bloginfo('stylesheet_directory'); ?>/images/Furniture1.jpg" class="left">
				<img src="<?php bloginfo('stylesheet_directory'); ?>/images/chair2.jpg" class="right">
			</div>
		</div><!-- #content -->
	</div><!-- #container -->

<?php //get_sidebar() ?>
<?php get_footer() ?>